### ISSUE TITLE
Further parameters in the `Fit` object

### ISSUE THREAD

**Issue by a-monsch** [dsavoiu/kafe2#133] opened 2020-04-20 10:13 UTC
I think it is very good that all the fits (`XYFit`, `HistFit`, `UnbinnedFit`...) have been simplified to the extent that you can only use `Fit`. The problem is that only the data and the model can be determined there.

I would appreciate it if the other arguments, the `cost_function` and the `minimizer` (and new ones if they arise), could also be set in `Fit`. It is possible to pass the cost function as a string (`"chi2"`, `"nll"`, ...) without setting it explicitly (`kafe2.XYCostFunction_Chi2(errors_to_use="covariance")` or similar).

Why can't one use this simplified version at `Fit`? Otherwise you have to revert back to the individual fit classes, which in the end limits `Fit` to the default settings only (is this intentional? See similarities with `Plot`).

**Comment by Citiroller** [comment] 2020-04-20 21:05
The `Fit` wrapper function is intended as a very simple user interface for beginners and people who don't know how kafe2 works yet. More parameters might be confusing for a newcomer.

Not all Cost Functions are available for all Fits, therefore error messages newcomers don't understand might appear.

A minimizer kwarg has been added in 8117cbf850b234dd9c2e7ab8e9bf4aa78d19d748.

**Comment by a-monsch** [comment] 2020-04-21 13:46
> The Fit wrapper function is intended as a very simple user interface for beginners and people who don't know how kafe2 works yet. More parameters might be confusing for a newcomer.

Okay, if this is really the target group, then it makes sense. But there is still the possibility to put this addition in `**kwargs` and use the default cost function when not calling it. This option would make it "invisible" to newcomers, but it would give you the possibility to access it after reading the documentation (See for example many of matplotlib's methods / the `minimizer_kwargs` argument in each individual fit class.).

> A minimizer kwarg has been added in `8117cbf`.

That's very good! If you have the target group in mind, you could also "disappear" the `minimizer` argument in the `**kwagrs` and let only those users use it who have had a look at the documentation.

This would probably require more implementation effort than telling users that if they want to be more specific, they should use the appropriate fit class. But with a versatile `Fit` class, like `Plot`, all the different types of fits could be hidden from the user.
For example, an advanced user would only set/replace one argument when revisiting code instead of again creating a specific object (even if the naming is intuitively) when using other data, etc.

**Comment by Citiroller** [comment] 2020-04-22 08:37
`**kwargs` could be added indeed. The problem is, that some fits have different argument names than others. So then, the individual fit classes could be used as well.
But it can't hurt to add kwargs.

**Comment by Citiroller** [comment] 2020-04-22 08:42
Added `**kwargs` in ecaaa62a2e562483ff16dfcd0d1fca3f3762fbe8. Closing this issue.

Btw. all or most fits support setting the cost function via a string. So setting it with a kwarg now should be no problem.

**Closed by Citiroller** 2020-04-22 08:42 UTC
Labels: feature request
